// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-8UTW93y1kxICKWPmoNf0zJSQ2hWUn0',
    appId: '1:661419483752:web:e4716786ae1c2b8ae391dd',
    messagingSenderId: '661419483752',
    projectId: 'skillswap-b1321',
    authDomain: 'skillswap-b1321.firebaseapp.com',
    storageBucket: 'skillswap-b1321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8sEoqjLsv9U-rqB9woEXBUt4iJpuWPA',
    appId: '1:661419483752:android:0042219346791400e391dd',
    messagingSenderId: '661419483752',
    projectId: 'skillswap-b1321',
    storageBucket: 'skillswap-b1321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-2e2bp0yRYQSwg7F55J7cED3aLG6sHo',
    appId: '1:661419483752:ios:2595401319e21119e391dd',
    messagingSenderId: '661419483752',
    projectId: 'skillswap-b1321',
    storageBucket: 'skillswap-b1321.appspot.com',
    androidClientId: '661419483752-am2oh07hr7nn155p6eqq4b1uq3o78kha.apps.googleusercontent.com',
    iosClientId: '661419483752-v5n8g6drbbpmlnati33v6okvuv4h1fbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-2e2bp0yRYQSwg7F55J7cED3aLG6sHo',
    appId: '1:661419483752:ios:2595401319e21119e391dd',
    messagingSenderId: '661419483752',
    projectId: 'skillswap-b1321',
    storageBucket: 'skillswap-b1321.appspot.com',
    androidClientId: '661419483752-am2oh07hr7nn155p6eqq4b1uq3o78kha.apps.googleusercontent.com',
    iosClientId: '661419483752-v5n8g6drbbpmlnati33v6okvuv4h1fbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );
}
