// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_Xf1Cxu6lq3qocdNRpxPoHSs5ucFR_U',
    appId: '1:331251895375:web:3924905ee6c36c21666e3a',
    messagingSenderId: '331251895375',
    projectId: 'skillswap-31798',
    authDomain: 'skillswap-31798.firebaseapp.com',
    storageBucket: 'skillswap-31798.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLTaGsu3hNJCTSpnfNc4U7Nh_QseqJ1M',
    appId: '1:331251895375:android:e25d3abfcf9c571e666e3a',
    messagingSenderId: '331251895375',
    projectId: 'skillswap-31798',
    storageBucket: 'skillswap-31798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSViLu_6LXKYiryq4DFaLbAi_qshSBbWM',
    appId: '1:331251895375:ios:da4baff66ca1e1c3666e3a',
    messagingSenderId: '331251895375',
    projectId: 'skillswap-31798',
    storageBucket: 'skillswap-31798.appspot.com',
    iosClientId: '331251895375-lto0sbgllm0a584qhh5ce9ic4isfc2ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSViLu_6LXKYiryq4DFaLbAi_qshSBbWM',
    appId: '1:331251895375:ios:da4baff66ca1e1c3666e3a',
    messagingSenderId: '331251895375',
    projectId: 'skillswap-31798',
    storageBucket: 'skillswap-31798.appspot.com',
    iosClientId: '331251895375-lto0sbgllm0a584qhh5ce9ic4isfc2ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );
}
